### ISSUE TITLE
app not starting on OLED65C97LA

### ISSUE THREAD

**Issue by fbartnitzek** [volkovmqx/cccbib#7]
I installed the app via webos brew.
The app launches with the logo but resulting in a black screen.

When running locally with [npm 16.19](https://webostv.developer.lge.com/develop/guides/js-service-basics#supported-nodejs-version) the app is starting and working for "regular" videos (and only displaying `404` in the div on "live" videos from 38c3).

In the webOS Dev Manager my Device versions are:
Firmware version: 05.40.61
webOS version: 4.10.0
SoC: o18

Unfortunately I don't see any Debug-Information or logs via the terminal, so here ends my npm / webos knowledge.

Could you have a look at supporting multiple device versions - I am happy to test ;-)

**Comment by jklmnn** [comment]
I have the same problem on a 65SM82007LA. I tried debugging the app as described [here](https://webostv.developer.lge.com/develop/tools/cli-dev-guide) with `ares-inspect`. However it seems the debugging interface on my TV is so old it requires Chrome version 68 to work which I haven't been able to gert to run so far unfortunately.

@fbartnitzek if you want to debug it on your TV you can run
```
ares-inspect -d <your device> org.webosbrew.cccbib
```
and it should spit out the link to the web debugger.

Given that your TV seems to be at least as old as mine you probably also need an old Chrome.

From the page I linked:
![image](https://github.com/user-attachments/assets/b24272e4-178c-40d8-8b94-7cdfa3d8e9c9)

**Comment by volkovmqx** [comment]
@jklmnn Thanks for showing how to debug! 
@fbartnitzek Unfortunately i don't have access to the old webos, but i am playing with the [simulator](https://webostv.developer.lge.com/develop/tools/simulator-installation) and i am trying old versions right now. However, logs as @jklmnn suggested would be helpful.

**Comment by volkovmqx** [comment]
Hello again, 

It seems that almost all the dependencies I’ve used have some bugs and aren’t supported by Chrome 68. Unfortunately, this means that i'll need to rewrite the app using older versions of those dependencies, or possibly explore some alternatives. I wish I had the capacity to tackle this right now, but I’m a bit swamped at the moment.
However, if you’re feeling inspired, I’d love for you to push a PR whenever you have the time and motivation! 

Another option to consider is updating your TV. I know this isn’t the most recommended route since it could mean losing your root privileges, but you could use developer mode along with a local cronjob to extend automatically the limit of 999 hours.

I will close this for now.

**Comment by jklmnn** [comment]
Thanks for taking a look into this! I tried getting Chrome 68 to work but I couldn't find a version that wouldn't crash on my system as soon as I opened a tab. As for my TV there doesn't seem to be an upgrade path other than buying  a new one unfortunately. It least I couldn't find any firmware that is newer than what I already have, neither unofficial nor official one.

My only suggestion would be to rename the issue into something along the lines "Support webOS < 6.0" and maybe keep it open as a feature request so that it's clear for other people who might run into the same issue.

**Comment by volkovmqx** [comment]
Alright, i took another look into the code and did some research, apparently with mantine 6 and some tweaks we can get this running into chrome 68 :) 
I've tested the main functionality and it's working in chrome 68, however, i need you guys to test it out in your TVs. i've created a PR here[](https://github.com/volkovmqx/cccbib/pull/8/commits/9828a1447adff38dbf94b3f2801dbe631f4631e4)

So you basically need to checkout to the branch, build it locally (check README.md) and deploy the IPK to your TV. Let me know if it's working (or not)

**Comment by jklmnn** [comment]
I tried the version from the PR it only shows a black screen (no logo at startup).

Just to be sure there is no misunderstanding. From how I understand it the problem is not that the app doesn't support Chrome 68 but the debugger on the TV. As far as I understand the process the app is being debugged on the TV itself and the TV creates a webpage that can be viewed and interacted with in Chrome. It uses Chrome's own inspection tools for debugging. And the problem I'm facing is that the webpage produced by my TV does not work in any newer Chrome version. So the problem with Chrome isn't that I can't interact with your app. I can't even interact with the debugging interface to begin with. The debugger fails way before the app is loaded.

So there may be a problem in the App that is specific to webOS but not Chrome. Is the emulator you're using able to run an older version of webOS? I have the same version as @fbartnitzek, 4.10.

And thanks again for taking the time to look into it!

**Comment by volkovmqx** [comment]
Unfortunately the minimum version that can be tested with the simulator is 6. If you suspect that the issue might not be with the Chrome/app itself but rather with the packaging or building process, we could try a different approach:

1. Find a WebOS app that’s working on your TV and is also based on TypeScript/JavaScript (you can check out [this link](https://repo.webosbrew.org/apps/)).
2. Compare the code between that app and yours to see if there are any differences—perhaps a different version of the @webosose/ares-cli package or some variations in the metadata.
3. Test your findings by building and deploying the IPK to your TV.

I know this might take some time, but I can’t think of any other solutions at the moment, especially since we don’t have any debug logs to work with.

If you need any help or have other ideas, feel free to reach out! I'm here to help :)

**Comment by jklmnn** [comment]
Thanks I'll take a look!

Btw you said you got it running in Chrome 68. Which platform where you running that Chrome on? If I get the Chrome itself running I may even be able to debug.

**Comment by volkovmqx** [comment]
I got it from the link you posted : https://webostv.developer.lge.com/develop/tools/cli-dev-guide

**Comment by jklmnn** [comment]
Yes, I got mine from there, too. But when I try to use it (Linux 64bit) it just tells me the tab crashed when I tried to load any page (not just the debugger).

**Comment by volkovmqx** [comment]
for me the only way is to run it is without sandbox. however, if that does not help you, and you have time, you can try to run it inside a virtual machine (ubuntu 16 or something).

**Comment by jklmnn** [comment]
The sandbox hint was what I was missing. Running it with `--no-sandbox` makes it work for me. I can open the debugger now and get the following error:
```
Uncaught ReferenceError: ResizeObserver is not defined
6bundle.js:2400 The above error occurred in the <l> component:

    at l (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:252:1432)
    at div
    at div
    at div
    at div
    at div
    at div
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2265:3170
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2205:2768
    at b (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:255:2169)
    at div
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2265:3170
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2478:288
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2139:4359
    at p
    at U (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:180:7195)
    at be (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:180:15944)
    at ge (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:180:14811)
    at B (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:167:9614)
    at i
    at c (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2025:458)
    at l (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2343:846)
    at d (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2340:1435)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.console.error @ bundle.js:2400
bundle.js:101 Uncaught ReferenceError: ResizeObserver is not defined
```
I uploaded the non-minified bundle.js I built from https://github.com/volkovmqx/cccbib/pull/8: [bundle.tar.gz](https://github.com/user-attachments/files/18337099/bundle.tar.gz)

Tbh I don't have enough JS experience to even tell if the error is originating from Chrome itself, the debugging page or actually from the app. Since it's in the bundle but not in the source code of the app I assume it's a dependency that does something unsupported?

Another hint that may be helpful for you is that the app seems to do something. Unless you have included all the thumbnails of the videos in the app it actually seems to download the video list with thumbnails correctly. When I look in the `Application` tab under `Frames` -> `top` -> `images` I can find what I think are the thumbnails from media.ccc.de:
![image](https://github.com/user-attachments/assets/a2d4a795-ae8c-4727-a537-7a7aa63cda64)

**Comment by volkovmqx** [comment]
Hmm, I think you are still using the new version of mantine. can you do a `rm -rf node_modules` and install again the new dependencies of the new branch by running `yarn` ?

**Comment by jklmnn** [comment]
The behavior seems to be the same however I'm now getting a slightly different log. This is the new bundle: 
[bundle.tar.gz](https://github.com/user-attachments/files/18386363/bundle.tar.gz)

and the new log is
```
bundle.js:2361 Uncaught ReferenceError: ResizeObserver is not definedinit @ bundle.js:2361S @ bundle.js:2361D @ bundle.js:2361(anonymous function) @ bundle.js:2355sh @ bundle.js:371Eh @ bundle.js:371Lh @ bundle.js:371(anonymous function) @ bundle.js:371Vh @ bundle.js:371(anonymous function) @ bundle.js:371cv @ bundle.js:371(anonymous function) @ bundle.js:371iv @ bundle.js:371qy @ bundle.js:371Gc @ bundle.js:371(anonymous function) @ bundle.js:371iv @ bundle.js:371(anonymous function) @ bundle.js:371Iy @ bundle.js:371w @ bundle.js:453_ @ bundle.js:453V @ bundle.js:453H.(anonymous function) @ bundle.js:1143S @ bundle.js:1143V @ bundle.js:1143
6bundle.js:371 The above error occurred in the <l> component:

    at l (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:462:1420)
    at div
    at div
    at div
    at div
    at div
    at div
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:55:1892
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:94:1980
    at b (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:465:2125)
    at main
    at div
    at div
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:55:1892
    at file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:49:1906
    at p
    at B (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:417:7195)
    at be (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:417:15944)
    at ge (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:417:14811)
    at U (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:404:9614)
    at c
    at i (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:2235:458)
    at g (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:16:2010)
    at M (file:///media/developer/apps/usr/palm/applications/org.webosbrew.cccbib/bundle.js:166:3320)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.Pp @ bundle.js:371Dp.r.callback @ bundle.js:371Vu @ bundle.js:371Ou @ bundle.js:371ch @ bundle.js:371Ch @ bundle.js:371e @ bundle.js:371zh @ bundle.js:371(anonymous function) @ bundle.js:371iv @ bundle.js:371qy @ bundle.js:371Gc @ bundle.js:371(anonymous function) @ bundle.js:371iv @ bundle.js:371(anonymous function) @ bundle.js:371Iy @ bundle.js:371w @ bundle.js:453_ @ bundle.js:453V @ bundle.js:453H.(anonymous function) @ bundle.js:1143S @ bundle.js:1143V @ bundle.js:1143
bundle.js:2361 Uncaught ReferenceError: ResizeObserver is not defined
```
I checked that the new bundle is actually different from the old one (assuming that they would be quite similar had I rebuilt it with the same node modules) however the original error still seems to be identical.
